apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
# ^^^^^^^^^ Takes care of the manifests and Kustomization will either look for kustomization.yaml within the path or if none found generate one that contains all Kubernetes manifests in it. 
metadata:
  name: example-gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: example-repo
  interval: 10m
  # interval here means interval after which the source resources to be recomputed and apply it to cluster: https://fluxcd.io/docs/components/kustomize/kustomization/#reconciliation
  path: ./4-gitops/manifests # Path tells where to find the files. Excellent for "monorepos" where you have multiple different applications in one repository, like the example repository.
  prune: true # This will make sure that deleting the file will delete the resource
  validation: client # Who validates the objects. Server or the client.
