apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: example-repo
  namespace: flux-system
  # NOTES SAHIL #1
spec:
  interval: 10m
  # url: https://github.com/kubernetes-hy/material-example
  url: https://github.com/sahilrajput03/devopswithkubernetes
  ref:
    # ORIGINALLY 
    # branch: master
    branch: main

  # NOTES SAHIL #1 HERE...
  # FYI(sahil): The `.metadata.name` and `.metadata.namespace` defined here
  # are referenced in other file `example.yml` file which is
  # of `kind: Kustomization`.
  #
  # FYI(sahil): Above defined namespace isn't actually used as namespace in our
  # cluster but it'll be consumed by flux and it'll be defined as label to
  # our deployment (verify via: `kc edit deployments.apps hashgenerator-dep`).
  #
  # FYI(sahil): The label would NOT be assigned to any pod.
  # kustomize.toolkit.fluxcd.io/namespace: flux-system
