apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: my-nats-repo
