apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
        # I ADDED SOPS-AGE SECRET(PRIVATE KEY FILE) TO FLUX USING BELOW USING BELOW COMMAND:
      # cat $SOPS_AGE_KEY_FILE | kubectl create secret generic sops-age --namespace=flux-system --from-file=age.agekey=/dev/stdin
  # interval: 2m0s
  interval: 10m0s
  # path: ./clusters/cluster0
  path: ./exercises/ex4-08/ex4-06/ex2-08-statefulsets/broadcaster-with-manifests/manifests-secrets-fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: project-repo

