apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-secrets
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
      # I added sops-age secret using my age private key file.
      # cat $SOPS_AGE_KEY_FILE | kubectl create secret generic sops-age --namespace=default --from-file=age.agekey=/dev/stdin
  interval: 1m0s
  # path: ./clusters/cluster0
  path: ./exercises/ex4-08/ex4-06/ex2-08-statefulsets/manifests-secrets-fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: project-repo

